### ISSUE TITLE
docker-compose 可以用吗？

### ISSUE THREAD

**Issue by Kayuii** [TRON-US/docker-tron-quickstart#5]
有docker-compose得yml模板吗？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by julesGoullee** [comment]
Like a docker-compose.yml file like this?

```
version: '3'

services:

  node-dev:
    image: trontools/quickstart:2.0.17
    environment:
      defaultBalance: '100000'
      showQueryString: 'true'
      showBody: 'true'
      formatJson: 'true'
      seed: 'your seed is awsome'
    ports:
      - 9090:9090

```
